# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - name: Backup .env
      run: |
          if [ -f .env ]; then mv .env /tmp/env_backup; fi
    - uses: actions/checkout@v4
    - name: Use Node.js 22v
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Restore .env
      run: |
          if [ -f /tmp/env_backup ]; then mv /tmp/env_backup .env; fi
    - run: npm ci
    - run: npm run build --if-present
    - name: Restart Backend with PM2
      run: |
        # This will try to restart, but if it's the first time after a reboot, it will START it instead.
        sudo pm2 restart backend || sudo pm2 start app.js --name "backend"
        sudo pm2 save
